Added updated logo to repo and changed header image in readme to use it
ThreeSixtyGiving/standard pull request #313
Opened 2021-12-28 09:58 UTC by mrshll1001

This PR adds a new file into the repo, `360standard-color.png`, taken from the [branding guidelines logo page](https://cdn.threesixtygiving.org/components/detail/logos.html) and updates the README file to point towards it.

2022-01-04 10:48 UTC, KDuerden commented on README.md
>  For more about the overall project, visit the main [360Giving website](http://threesixtygiving.com/about/).
update to current website url: https://www.threesixtygiving.org/

2022-01-04 10:53 UTC, KDuerden commented on README.md
>  For more about the overall project, visit the main [360Giving website](http://threesixtygiving.com/about/).
also be good to update url on row 12 from http://www.threesixtygiving.org/standard to https://standard.threesixtygiving.org/en/latest/

2022-01-04 10:55 UTC, KDuerden commented on README.md
>  360Giving aims to help UK grant makers and philanthropists to publish their grant information online in an easy to use way.  We are motivated by a commitment to the value of open data and strategic f
update text to align with current mission statement: 

360Giving's mission is to help UK funders publish open, standardised grants data, and empower people to use it to improve charitable giving

2022-01-04 10:55 UTC, KDuerden requested changes
Thanks. That's fine but I've added some comment to update the website links and updating the statement about 360Giving to match our mission statement.

2022-01-04 12:34 UTC, Bjwebb commented
If we add the logo to the repo, we need to add a sentence to the license file, as we do for CoVE:

> Note: This license doesn't apply to the 360Giving theme and related assets (such as the logo).

2023-06-13 13:10 UTC, mrshll1001 commented
I've updated the PR and made the changes noted. Let me know if there's anything else :-)

2023-06-21 09:45 UTC, mariongalley approved these changes

2023-06-21 09:49 UTC, KDuerden commented on README.md
> +Full documentation of the data standard is provided at [http://www.threesixtygiving.org/standard](http://www.threesixtygiving.org/standard/en/latest)
This url is wrong, it needs to be https://standard.threesixtygiving.org/en/latest/

2023-06-21 09:53 UTC, KDuerden commented on README.md
> +For more about the overall project, visit the main [360Giving website](http://threesixtygiving.org/).
It would be good to link to the secure url version - https://www.threesixtygiving.org/

2023-06-21 09:55 UTC, KDuerden commented on LICENSE.md
> +  <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Thi
It would be good to link to the secure version in these links - https://creativecommons.org/licenses/by/4.0/

2023-06-21 11:34 UTC, KDuerden requested changes
I've added comments on three areas that I think need updating - to use the secure version of each website and to correct the link to the Standard website which is currently incorrect

2023-08-10 09:26 UTC, mrshll1001 commented
Cheers @KDuerden, I've amended as per suggestions. Agree we should promote https where possible and explicitly point to the latest branch of the standard docs!

2023-08-18 08:45 UTC, KDuerden approved these changes
I've reviewed the changes and I'm happy that the updates and confirm that this is a non-normative change, so doesn't need to go through the Standard governance processes.

2023-08-21 09:15 UTC, merged