Add readthedocs configuration file
ThreeSixtyGiving/standard pull request #368
Opened 2023-08-10 10:00 UTC by mrshll1001

For upcoming RTD version 2 changes, which would break our docs builds.

I based this on a RTD file for another project, so would appreciate someone reviewing to make sure this matches the needs for this build.

2023-08-10 10:03 UTC, mrshll1001 commented
The docs built, and are available for checking [here](https://standard.threesixtygiving.org/en/rtd-v2-compatibility/#)

2023-08-10 19:44 UTC, Bjwebb commented
You need to set the builder to dirhtml like https://github.com/OpenDataServices/flatten-tool/blob/main/.readthedocs.yaml#L17

Otherwise the endings of URLs will change.

Compare https://standard.threesixtygiving.org/en/latest/guidance/before-starting/
https://standard.threesixtygiving.org/en/latest/guidance/before-starting/

2023-08-10 19:45 UTC, Bjwebb requested changes
You need to set the builder to dirhtml like https://github.com/OpenDataServices/flatten-tool/blob/main/.readthedocs.yaml#L17

Otherwise the endings of URLs will change.

Compare https://standard.threesixtygiving.org/en/latest/guidance/before-starting/
https://standard.threesixtygiving.org/en/latest/guidance/before-starting/

2023-08-16 12:19 UTC, Bjwebb approved these changes

2023-08-17 09:10 UTC, merged